package com.bnr.group.model.views;

import java.util.HashMap;

import oracle.jbo.RowSet;
import oracle.jbo.server.ProgrammaticViewRowImpl;
import oracle.jbo.server.ViewAttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 03 22:42:26 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupSearchPVORowImpl extends ProgrammaticViewRowImpl {
    /**
     * createRowData - for custom java data source support.
     * Overridden to initialize the dataProvier for newly created row.
     * Used for updateable View Objects.
     */
    public Object createRowData(HashMap attrNameValueMap) {
        Object value = super.createRowData(attrNameValueMap);
        return value;
    }

    /**
     * convertToSourceType - for custom java data source support.
     * Overridden to provide custom implementation for conversions of a value
     * from attribute java type to datasource column/field type.
     * Not required in most cases.
     */
    public Object convertToSourceType(ViewAttributeDefImpl attrDef, String sourceType, Object val) {
        Object value = super.convertToSourceType(attrDef, sourceType, val);
        return value;
    }

    /**
     * convertToAttributeType - for custom java data source support.
     * Overridden to provide custom implementation for conversions of a value
     *  from datasource/column field type to attribute java type.
     * Not required in most cases.
     */
    public Object convertToAttributeType(ViewAttributeDefImpl attrDef, Class javaTypeClass, Object val) {
        Object value = super.convertToAttributeType(attrDef, javaTypeClass, val);
        return value;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GroupId,
        GroupCode,
        GroupName,
        GroupSearchVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int GROUPID = AttributesEnum.GroupId.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int GROUPNAME = AttributesEnum.GroupName.index();
    public static final int GROUPSEARCHVO1 = AttributesEnum.GroupSearchVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GroupSearchPVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute GroupId.
     * @return the GroupId
     */
    public Integer getGroupId() {
        return (Integer) getAttributeInternal(GROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupId.
     * @param value value to set the  GroupId
     */
    public void setGroupId(Integer value) {
        setAttributeInternal(GROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupCode.
     * @return the GroupCode
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupCode.
     * @param value value to set the  GroupCode
     */
    public void setGroupCode(String value) {
        setAttributeInternal(GROUPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupName.
     * @return the GroupName
     */
    public String getGroupName() {
        return (String) getAttributeInternal(GROUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupName.
     * @param value value to set the  GroupName
     */
    public void setGroupName(String value) {
        setAttributeInternal(GROUPNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupSearchVO1.
     */
    public RowSet getGroupSearchVO1() {
        return (RowSet) getAttributeInternal(GROUPSEARCHVO1);
    }
}

